// Parity against the Python implementation.
//
// Every fixture here was generated by backend/tools/dump_golden.py from the same items
// dump the committed catalog is built from. A failure means the JS port diverged from
// the behavior the Flask app shipped - including its bugs, which are pinned on purpose so
// that a mismatch can never be ambiguous between "porting mistake" and "intended fix".

import test from 'node:test';
import assert from 'node:assert/strict';

import { setCatalog } from '../src/lib/catalog.js';
import { buildVariant, equivalentVariants, serializeVariant } from '../src/lib/items.js';
import { findDefinition } from '../src/lib/catalog.js';
import { searchItems } from '../src/lib/search.js';
import { planBatches, fetchPrices } from '../src/lib/prices.js';
import { itemImageUrl, priceQueryUrl } from '../src/lib/urls.js';
import { optimizeLoadoutWithCities } from '../src/lib/optimizer.js';
import { getConfig } from '../src/lib/api.js';
import { catalogData, golden } from './helpers.mjs';

setCatalog(catalogData());

test('config payload matches Python', () => {
  assert.deepEqual(getConfig(), golden('config.json'));
});

test('search returns the same items, in the same order, across the full matrix', () => {
  const matrix = golden('search.json').matrix;
  let compared = 0;
  for (const [key, expected] of Object.entries(matrix)) {
    const [query, language, slotKey] = key.split('|');
    const slot = slotKey === '*' ? null : slotKey;
    const actual = searchItems(query, language, slot).map((item) => item.unique_name);
    assert.deepEqual(actual, expected, `search mismatch for ${JSON.stringify(key)}`);
    compared += 1;
  }
  assert.ok(compared > 300, `expected a broad matrix, compared only ${compared}`);
});

test('search payloads match in full, not just in unique_name order', () => {
  const deep = golden('search.json').deep;
  for (const [key, expected] of Object.entries(deep)) {
    const [query, language, slotKey] = key.split('|');
    const slot = slotKey === '*' ? null : slotKey;
    assert.deepEqual(searchItems(query, language, slot), expected, `deep mismatch for ${key}`);
  }
});

test('serialized items match, including per-tier names and market aliases', () => {
  for (const [key, expected] of Object.entries(golden('item.json'))) {
    const [template, tier, enchantment, language] = key.split('|');
    const definition = findDefinition(template);
    assert.ok(definition, `${template} should resolve`);
    const variant = buildVariant(definition, Number(tier), Number(enchantment));
    assert.deepEqual(serializeVariant(variant, language), expected, `item mismatch for ${key}`);
  }
});

test('equivalent variants match', () => {
  for (const [key, expected] of Object.entries(golden('equivalents.json'))) {
    const [template, tier, enchantment] = key.split('|');
    const definition = findDefinition(template);
    const variant = buildVariant(definition, Number(tier), Number(enchantment));
    const actual = equivalentVariants(variant).map((candidate) => candidate.unique_name);
    assert.deepEqual(actual, expected, `equivalents mismatch for ${key}`);
  }
});

test('generated URLs match byte for byte', () => {
  const expected = golden('urls.json');
  for (const [key, url] of Object.entries(expected.price_query_url)) {
    const [uniqueName, region, cityList] = key.split('|');
    const cities = cityList === '' ? [] : cityList.split(',');
    assert.equal(priceQueryUrl(uniqueName, region, cities), url, `price url mismatch for ${key}`);
  }
  for (const [key, url] of Object.entries(expected.item_image_url)) {
    const [uniqueName, quality, locale] = key.split('|');
    assert.equal(itemImageUrl(uniqueName, Number(quality), locale), url, `image url for ${key}`);
  }
});

test('price requests batch at the same boundaries', () => {
  const expected = golden('batches.json');
  const inputs = {
    short: Array.from({ length: 10 }, (_, index) => `T4_MAIN_SWORD@${index % 5}`),
    long_500: Array.from(
      { length: 500 },
      (_, index) => `T${4 + (index % 5)}_ARMOR_PLATE_SET${index}@${index % 5}`,
    ),
    duplicates_collapsed: ['T4_MAIN_SWORD', 'T4_MAIN_SWORD', 'T5_CAPE', 'T4_MAIN_SWORD'],
  };
  for (const [name, names] of Object.entries(inputs)) {
    const deduped = [...new Set(names)];
    assert.deepEqual(planBatches(deduped), expected[name], `batch split mismatch for ${name}`);
  }
});

// The fixture stores the *result* of fetch_prices. Replaying it through a fake HTTP layer
// (rather than injecting the finished table) keeps the real batching and response-folding
// code under test, including the zero-price and tie-break rules.
function stubFetchFromFixture(table) {
  const FIXED_NOW = 1753000000000;
  const fetchImpl = async (url) => {
    const itemSegment = decodeURIComponent(url.split('/prices/')[1].split('.json')[0]);
    const rows = [];
    for (const uniqueName of itemSegment.split(',')) {
      const cityPrices = table[uniqueName] || {};
      for (const [city, record] of Object.entries(cityPrices)) {
        rows.push({
          item_id: uniqueName,
          city,
          quality: record.quality,
          sell_price_min: record.sell_price_min,
          buy_price_max: record.buy_price_max,
          sell_price_min_date: record.updated_at,
        });
      }
    }
    return { ok: true, json: async () => rows };
  };
  return { fetchImpl, now: () => FIXED_NOW };
}

test('optimizer output matches Python against a recorded price table', async () => {
  const { cases, results } = golden('optimize.json');
  const fetchOptions = stubFetchFromFixture(golden('prices.fixture.json'));

  for (const testCase of cases) {
    const actual = await optimizeLoadoutWithCities({
      loadout: testCase.loadout,
      region: testCase.region,
      language: testCase.language,
      cities: testCase.cities,
      fetchOptions,
    });
    assert.deepEqual(actual, results[testCase.name], `optimize mismatch for ${testCase.name}`);
  }
});

test('the recorded table round-trips through the real fetch path', async () => {
  const table = golden('prices.fixture.json');
  const names = Object.keys(table);
  const prices = await fetchPrices(names, 'americas', [
    'Caerleon',
    'Martlock',
    'Thetford',
    'Bridgewatch',
  ], stubFetchFromFixture(table));
  for (const name of names) {
    assert.deepEqual(prices.get(name), table[name], `price record mismatch for ${name}`);
  }
});
